### ISSUE TITLE
Aperture offsets when importing MAD sequence are treated as coordinate transforms

### ISSUE THREAD

**Issue by eltos** [xsuite/xsuite#227] opened 2022-11-14 10:21 UTC
**Observed behaviour:**  
When importing MAD elements with aperture offsets and tilts, these are treated as change in the coordinate system by adding `SRotation` and `XYShift` elements before and after the aperture (see [source](https://github.com/xsuite/xtrack/blob/a3081417b711d871a20ad96f57a55c7132903623/xtrack/mad_loader.py#L330-L370)).
While this works, it can lead to counter-intuitive situations e.g. when calculating the closed orbit via twiss.
The closed orbit makes an apprupt infinitesimal jump due to the change in coordiante systems to account for the (still symmetrically placed) aperture.

**Expected behaviour:**  
Since Xsuite supports non-symetric aperture limits (in contrast to MAD-X), I would have expected an aperture offset/tilt to be treated by shifting/tilting the [vertices](https://github.com/xsuite/xtrack/blob/a3081417b711d871a20ad96f57a55c7132903623/xtrack/mad_loader.py#L378-L379) of the apperture directly (and keeping the coordinate system as-is). The closed orbit would then be continuous as expected.

Is there a specific reason why aperture offsets are treated by shifting the beam instead of shifting the aperture?

**Comment by giadarol** [comment] 2022-11-14 14:23
A relatively simple trick is that the beam is in the MAD-X reference frame at the entrance of each drift. So, as long as only thin elements are used, the beam shape is available in the MAD-X frame at all locations.

I close the issue for now, as the code has intended behaviour. 

In the future, we might develop a post-processing tool to change the coordinates a posteriori (to be attached to the monitor element for example...)

**Closed by giadarol** 2022-11-14 14:23 UTC

**Comment by eltos** [comment] 2022-11-14 14:28
Thanks @rdemaria and @giadarol for the quick respone and the explanation, I understand your reasoning.
In my use-case it is only two `LimitRect` elements with a simple horizontal shift such that only the `min_x` and `max_x` values change. I have now removed them from the sequence and insert them manually into the line after the madloader import which works for me.
