### ISSUE TITLE
twiss in a range of elements

### ISSUE THREAD

**Issue by rdemaria** [xsuite/xsuite#158] opened 2022-09-19 09:11 UTC
Needed features:
- select start/end point  -> start, n_element @giadarol 
- use initial orbit and W matrix (refactor dispersion calculation using W) @giadarol 
- insert flags to skip optional calculations (eta, trev, ..)  @giadarol 
- compute W from twiss parameters @rdemaria

**Comment by giadarol** [comment] 2022-10-16 12:31
duplicate of #172

**Closed by giadarol** 2022-10-16 12:31 UTC
Labels: enhancement
